vlib work
vlib msim

vlib msim/xil_defaultlib
vlib msim/xpm
vlib msim/jtag_axi
vlib msim/lib_cdc_v1_0_2
vlib msim/proc_sys_reset_v5_0_9
vlib msim/blk_mem_gen_v8_3_2
vlib msim/xbip_dsp48_wrapper_v3_0_4
vlib msim/xbip_utils_v3_0_6
vlib msim/xbip_pipe_v3_0_2
vlib msim/xbip_dsp48_macro_v3_0_12

vmap xil_defaultlib msim/xil_defaultlib
vmap xpm msim/xpm
vmap jtag_axi msim/jtag_axi
vmap lib_cdc_v1_0_2 msim/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_9 msim/proc_sys_reset_v5_0_9
vmap blk_mem_gen_v8_3_2 msim/blk_mem_gen_v8_3_2
vmap xbip_dsp48_wrapper_v3_0_4 msim/xbip_dsp48_wrapper_v3_0_4
vmap xbip_utils_v3_0_6 msim/xbip_utils_v3_0_6
vmap xbip_pipe_v3_0_2 msim/xbip_pipe_v3_0_2
vmap xbip_dsp48_macro_v3_0_12 msim/xbip_dsp48_macro_v3_0_12

vlog -work xil_defaultlib -64 -incr -sv "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
"C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
"C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
"C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
"C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
"C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
"C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \

vcom -work xpm -64 -93 \
"C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work jtag_axi -64 -incr "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../ipstatic/jtag_axi/hdl/jtag_axi_v1_1_rfs.v" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/sim/risc_jtag_axi4_lite.v" \

vcom -work lib_cdc_v1_0_2 -64 -93 \
"../../../ipstatic/lib_cdc_v1_0_2/hdl/src/vhdl/cdc_sync.vhd" \

vcom -work proc_sys_reset_v5_0_9 -64 -93 \
"../../../ipstatic/proc_sys_reset_v5_0_9/hdl/src/vhdl/upcnt_n.vhd" \
"../../../ipstatic/proc_sys_reset_v5_0_9/hdl/src/vhdl/sequence_psr.vhd" \
"../../../ipstatic/proc_sys_reset_v5_0_9/hdl/src/vhdl/lpf.vhd" \
"../../../ipstatic/proc_sys_reset_v5_0_9/hdl/src/vhdl/proc_sys_reset.vhd" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_reset/sim/risc_reset.vhd" \

vlog -work blk_mem_gen_v8_3_2 -64 -incr "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../ipstatic/blk_mem_gen_v8_3_2/simulation/blk_mem_gen_v8_3.v" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_registers_memory/sim/risc_registers_memory.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal_clk_wiz.v" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal.v" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external_clk_wiz.v" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external.v" \

vcom -work xbip_dsp48_wrapper_v3_0_4 -64 -93 \
"../../../ipstatic/xbip_dsp48_wrapper_v3_0_4/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

vcom -work xbip_utils_v3_0_6 -64 -93 \
"../../../ipstatic/xbip_utils_v3_0_6/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

vcom -work xbip_pipe_v3_0_2 -64 -93 \
"../../../ipstatic/xbip_pipe_v3_0_2/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
"../../../ipstatic/xbip_pipe_v3_0_2/hdl/xbip_pipe_v3_0.vhd" \

vcom -work xbip_dsp48_macro_v3_0_12 -64 -93 \
"../../../ipstatic/xbip_dsp48_macro_v3_0_12/hdl/xbip_dsp48_macro_v3_0_vh_rfs.vhd" \
"../../../ipstatic/xbip_dsp48_macro_v3_0_12/hdl/xbip_dsp48_macro_v3_0.vhd" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_alu_dsp/sim/risc_alu_dsp.vhd" \

vlog -work blk_mem_gen_v8_3_2 -64 -incr "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_shared_memory_8K/sim/risc_shared_memory_8K.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/sim/risc_vio.v" \

vlog -work blk_mem_gen_v8_3_2 -64 -incr "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_program_memory/sim/risc_program_memory.v" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/sim/risc_ila.v" \

vlog -work blk_mem_gen_v8_3_2 -64 -incr "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_data_memory/sim/risc_data_memory.v" \

vlog -work xil_defaultlib -64 -incr -sv "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/logic_axi4_lite_pkg.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/logic_axi4_lite_if.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_stack.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite_wrapper.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_instruction_decode_pkg.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_alu_pkg.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_registers.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_interrupt_controller.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_instruction_decode.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clocking.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_axi_driver.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_alu.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_axi_slave_driver.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc.sv" \
"../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_core_verilog_wrapper.sv" \

vlog -work xil_defaultlib -64 -incr "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src" "+incdir+../../../ipstatic/clk_wiz_v5_3_0" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" "+incdir+../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
"../../../../RISC.srcs/sources_1/ip/risc_0/hdl/risc_v0_1.v" \
"../../../../RISC.srcs/sources_1/ip/risc_0/sim/risc_0.v" \

vlog -work xil_defaultlib "glbl.v"

