# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/PROJEKT/PICOBLAZE/Picoblaze/Picoblaze.srcs/sources_1/ip/ila_debug/ila_debug.xci
# IP: The module: 'ila_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PROJEKT/PICOBLAZE/Picoblaze/Picoblaze.srcs/sources_1/ip/ila_debug/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/PROJEKT/PICOBLAZE/Picoblaze/Picoblaze.srcs/sources_1/ip/ila_debug/ila_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: D:/PROJEKT/PICOBLAZE/Picoblaze/Picoblaze.srcs/sources_1/ip/ila_debug/ila_debug.xci
# IP: The module: 'ila_debug' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/PROJEKT/PICOBLAZE/Picoblaze/Picoblaze.srcs/sources_1/ip/ila_debug/ila_v6_1/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/PROJEKT/PICOBLAZE/Picoblaze/Picoblaze.srcs/sources_1/ip/ila_debug/ila_debug_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_debug'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
