# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/risc_0.xci
# IP: The module: 'risc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/risc_jtag_axi4_lite.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_jtag_axi4_lite || ORIG_REF_NAME==risc_jtag_axi4_lite}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_reset/risc_reset.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_reset || ORIG_REF_NAME==risc_reset}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_registers_memory/risc_registers_memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_registers_memory || ORIG_REF_NAME==risc_registers_memory}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_clock_internal || ORIG_REF_NAME==risc_clock_internal}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_clock_external || ORIG_REF_NAME==risc_clock_external}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_alu_dsp/risc_alu_dsp.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_alu_dsp || ORIG_REF_NAME==risc_alu_dsp}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_shared_memory_8K/risc_shared_memory_8K.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_shared_memory_8K || ORIG_REF_NAME==risc_shared_memory_8K}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_vio/risc_vio.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_vio || ORIG_REF_NAME==risc_vio}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_program_memory/risc_program_memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_program_memory || ORIG_REF_NAME==risc_program_memory}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_ila/risc_ila.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_ila || ORIG_REF_NAME==risc_ila}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_data_memory/risc_data_memory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_data_memory || ORIG_REF_NAME==risc_data_memory}]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/jtag_axi/constraints/jtag_axi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_jtag_axi4_lite || ORIG_REF_NAME==risc_jtag_axi4_lite}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_reset/risc_reset.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_reset || ORIG_REF_NAME==risc_reset}] {/U0 }]/U0 ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_registers_memory/risc_registers_memory_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_clock_internal || ORIG_REF_NAME==risc_clock_internal}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_clock_internal || ORIG_REF_NAME==risc_clock_internal}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_clock_external || ORIG_REF_NAME==risc_clock_external}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_shared_memory_8K/risc_shared_memory_8K_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_vio/risc_vio.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_vio || ORIG_REF_NAME==risc_vio}]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_program_memory/risc_program_memory_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_ila || ORIG_REF_NAME==risc_ila}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_ila/risc_ila_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_data_memory/risc_data_memory_ooc.xdc

# IP: D:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/risc_0.xci
# IP: The module: 'risc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/risc_jtag_axi4_lite.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_jtag_axi4_lite || ORIG_REF_NAME==risc_jtag_axi4_lite}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_reset/risc_reset.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_reset || ORIG_REF_NAME==risc_reset}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_registers_memory/risc_registers_memory.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_registers_memory || ORIG_REF_NAME==risc_registers_memory}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_clock_internal || ORIG_REF_NAME==risc_clock_internal}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_clock_external || ORIG_REF_NAME==risc_clock_external}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_alu_dsp/risc_alu_dsp.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_alu_dsp || ORIG_REF_NAME==risc_alu_dsp}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_shared_memory_8K/risc_shared_memory_8K.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_shared_memory_8K || ORIG_REF_NAME==risc_shared_memory_8K}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_vio/risc_vio.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_vio || ORIG_REF_NAME==risc_vio}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_program_memory/risc_program_memory.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_program_memory || ORIG_REF_NAME==risc_program_memory}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_ila/risc_ila.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_ila || ORIG_REF_NAME==risc_ila}]

# IP: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_data_memory/risc_data_memory.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_data_memory || ORIG_REF_NAME==risc_data_memory}]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/jtag_axi/constraints/jtag_axi.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_jtag_axi4_lite || ORIG_REF_NAME==risc_jtag_axi4_lite}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_reset/risc_reset.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_reset || ORIG_REF_NAME==risc_reset}] {/U0 }]/U0 ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_registers_memory/risc_registers_memory_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_clock_internal || ORIG_REF_NAME==risc_clock_internal}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_clock_internal || ORIG_REF_NAME==risc_clock_internal}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_clock_external || ORIG_REF_NAME==risc_clock_external}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_shared_memory_8K/risc_shared_memory_8K_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_vio/risc_vio.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==risc_vio || ORIG_REF_NAME==risc_vio}]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_program_memory/risc_program_memory_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==risc_ila || ORIG_REF_NAME==risc_ila}] {/inst }]/inst ]]

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_ila/risc_ila_ooc.xdc

# XDC: d:/PROJEKT/PICOBLAZE/RISC/RISC.srcs/sources_1/ip/risc_0/src/risc_data_memory/risc_data_memory_ooc.xdc
