#!/bin/bash -f
# Vivado (TM) v2016.1 (64-bit)
#
# Filename    : risc_0.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Oct 22 19:16:04 +0200 2020
# IP Build 1537824 on Fri Apr  8 04:28:57 MDT 2016 
#
# usage: risc_0.sh [-help]
# usage: risc_0.sh [-lib_map_path]
# usage: risc_0.sh [-noclean_files]
# usage: risc_0.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'risc_0.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64 -timescale=1ps/1ps"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Script info
echo -e "risc_0.sh - Script generated by export_simulation (Vivado v2016.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_base.sv" \
    "C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_dpdistram.sv" \
    "C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_dprom.sv" \
    "C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_sdpram.sv" \
    "C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_spram.sv" \
    "C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_sprom.sv" \
    "C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_memory/hdl/xpm_memory_tdpram.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2016.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work jtag_axi $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../ipstatic/jtag_axi/hdl/jtag_axi_v1_1_rfs.v" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/sim/risc_jtag_axi4_lite.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/lib_cdc_v1_0_2/hdl/src/vhdl/cdc_sync.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_9 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0_9/hdl/src/vhdl/upcnt_n.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0_9/hdl/src/vhdl/sequence_psr.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0_9/hdl/src/vhdl/lpf.vhd" \
    "$ref_dir/../../../ipstatic/proc_sys_reset_v5_0_9/hdl/src/vhdl/proc_sys_reset.vhd" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_reset/sim/risc_reset.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../ipstatic/blk_mem_gen_v8_3_2/simulation/blk_mem_gen_v8_3.v" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_registers_memory/sim/risc_registers_memory.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal_clk_wiz.v" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clock_internal/risc_clock_internal.v" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external_clk_wiz.v" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clock_external/risc_clock_external.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/xbip_dsp48_wrapper_v3_0_4/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/xbip_utils_v3_0_6/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_2 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/xbip_pipe_v3_0_2/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../ipstatic/xbip_pipe_v3_0_2/hdl/xbip_pipe_v3_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_macro_v3_0_12 $vhdlan_opts \
    "$ref_dir/../../../ipstatic/xbip_dsp48_macro_v3_0_12/hdl/xbip_dsp48_macro_v3_0_vh_rfs.vhd" \
    "$ref_dir/../../../ipstatic/xbip_dsp48_macro_v3_0_12/hdl/xbip_dsp48_macro_v3_0.vhd" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_alu_dsp/sim/risc_alu_dsp.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_shared_memory_8K/sim/risc_shared_memory_8K.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/sim/risc_vio.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_program_memory/sim/risc_program_memory.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/sim/risc_ila.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_data_memory/sim/risc_data_memory.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/logic_axi4_lite_pkg.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/logic_axi4_lite_if.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_stack.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite_wrapper.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_instruction_decode_pkg.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_alu_pkg.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_registers.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_interrupt_controller.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_instruction_decode.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_clocking.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_axi_driver.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_alu.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_axi_slave_driver.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc.sv" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_core_verilog_wrapper.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src" +incdir+"$ref_dir/../../../ipstatic/clk_wiz_v5_3_0" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ila_v6_1_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_ila/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_jtag_axi4_lite/xsdbs_v1_0_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/ltlib_v1_0_0/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/vio_v3_0_11/hdl" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbm_v1_1_2/hdl/verilog" +incdir+"$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/src/risc_vio/xsdbs_v1_0_2/hdl/verilog" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/hdl/risc_v0_1.v" \
    "$ref_dir/../../../../RISC.srcs/sources_1/ip/risc_0/sim/risc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.risc_0 xil_defaultlib.glbl -o risc_0_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./risc_0_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./risc_0.sh -help\" for more information)\n"
        exit 1
      fi
     create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
     create_lib_mappings $2
  esac

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Create design library directory paths and define design library mappings in cds.lib
create_lib_mappings()
{
  libs=(xil_defaultlib xpm jtag_axi lib_cdc_v1_0_2 proc_sys_reset_v5_0_9 blk_mem_gen_v8_3_2 xbip_dsp48_wrapper_v3_0_4 xbip_utils_v3_0_6 xbip_pipe_v3_0_2 xbip_dsp48_macro_v3_0_12)
  file="synopsys_sim.setup"
  dir="vcs"

  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  if [[ -e $dir ]]; then
    rm -rf $dir
  fi

  touch $file
  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#libs[*]}; i++ )); do
    lib="${libs[i]}"
    lib_dir="$dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
      mapping="$lib : $dir/$lib"
      echo $mapping >> $file
    fi
  done
  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi

}
# Remove generated data from the previous run and re-create setup files/library mappings
reset_run()
{
  files_to_remove=(ucli.key risc_0_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc risc_0_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./risc_0.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi

}

# Script usage
usage()
{
  msg="Usage: risc_0.sh [-help]\n\
Usage: risc_0.sh [-lib_map_path]\n\
Usage: risc_0.sh [-reset_run]\n\
Usage: risc_0.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
